name: Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: true
      matrix:
        os:
          - self-hosted
          # - windows-latest
          # - macos-latest

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install ninja-build tool (must be after Qt due PATH changes)
        if: ${{ runner.os == 'Windows' }}
        uses: turtlesec-no/get-ninja@main

      - name: Make sure MSVC is found when Ninja generator is in use
        if: ${{ runner.os == 'Windows' }}
        uses: ilammy/msvc-dev-cmd@v1

      - name: Checkout qt-embedder
        uses: actions/checkout@v4

      - name: Configure project
        run: cmake -S . -B ./build-dev --preset dev

      - name: Build Project ${{ matrix.preset.build_preset_arg }}
        run: cmake --build ./build-dev

      - name: Build example
        run: |
          ./build_example.sh
