name: Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: true
      matrix:
        os:
          - ubuntu-latest
          # - windows-latest
          # - macos-latest

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install Qt
        uses: jurplel/install-qt-action@v3
        with:
          version: 6.7.3
          cache: true

      - name: Install ninja-build tool (must be after Qt due PATH changes)
        if: ${{ runner.os == 'Windows' }}
        uses: turtlesec-no/get-ninja@main

      - name: Make sure MSVC is found when Ninja generator is in use
        if: ${{ runner.os == 'Windows' }}
        uses: ilammy/msvc-dev-cmd@v1

      - name: Install dependencies on Ubuntu
        if: ${{ runner.os == 'Linux' }}
        run: |
          sudo apt update -qq
          sudo apt install ninja-build lld xvfb -y

      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.24.0'
          channel: 'stable'

      - name: Checkout qt-embedder
        uses: actions/checkout@v4

      - name: Checkout flutter engine
        uses: actions/checkout@v4
        with:
          repo: iamsergio/engine.git
          ref: wip/multiwindow
          path: ${{ github.workspace}}/../engine

      - name: test
        run: ls ${{ github.workspace}}/..


      # - name: Configure project
      #   run: cmake -S . -B ./build-debug --preset debug

      # - name: Build Project ${{ matrix.preset.build_preset_arg }}
      #   run: cmake --build ./build-debug
