name: Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: true
      matrix:
        os:
          - ubuntu-24.04
        preset:
          - dev
          - rel

    steps:
      - name: Install Qt
        uses: jurplel/install-qt-action@v4
        with:
          version: 6.6.0
          cache: true

      - name: Checkout qt-embedder
        uses: actions/checkout@v4
        with:
          submodules: true

      - name: Install clang
        run: sudo apt-get update && sudo apt-get install -y clang ninja-build libgtk-3-dev unzip  libssl-dev lld curl wget gdebi-core libdbus-glib-1-2

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable
          cache: true
          flutter-version: 3.32.7
        run: flutter precache --linux

      - name: Download flutter engine
        run: sh download_engine.sh
        env:
          GH_TOKEN: ${{ github.token }}

      - name: Configure project
        run: cmake -S . -B ./build-${{ matrix.preset }} --preset ${{ matrix.preset }}

      - name: Build Project
        run: cmake --build ./build-${{ matrix.preset }}

      - name: Build example
        run: |
          ./build_example.sh
